// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW7MWEGD3EOqjSGjjW6ZVsE1rPFxPhFJU',
    appId: '1:804181808087:web:f20c014530d8ccf4103192',
    messagingSenderId: '804181808087',
    projectId: 'walesa-5f34e',
    authDomain: 'walesa-5f34e.firebaseapp.com',
    storageBucket: 'walesa-5f34e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBgeD0vm31ecy9QF-sAr-NLHldsNb8p4o',
    appId: '1:804181808087:android:4b47ee94cd24a3ac103192',
    messagingSenderId: '804181808087',
    projectId: 'walesa-5f34e',
    storageBucket: 'walesa-5f34e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgYj58bOseDtiU4RF2Kx3r5MZg3-CExpQ',
    appId: '1:804181808087:ios:e2260e6956347521103192',
    messagingSenderId: '804181808087',
    projectId: 'walesa-5f34e',
    storageBucket: 'walesa-5f34e.appspot.com',
    iosClientId: '804181808087-n8acmoo7dajcp5k317di6t484ridn4na.apps.googleusercontent.com',
    iosBundleId: 'com.example.walesa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgYj58bOseDtiU4RF2Kx3r5MZg3-CExpQ',
    appId: '1:804181808087:ios:4eadc2db1fd73bcd103192',
    messagingSenderId: '804181808087',
    projectId: 'walesa-5f34e',
    storageBucket: 'walesa-5f34e.appspot.com',
    iosClientId: '804181808087-bfq0st9ht47ln00hajrjrchi969q8dkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.walesa.RunnerTests',
  );
}
